---
title: "BEE 4750 Homework 2: Systems Feedbacks and Stability"
pdf-title: "BEE 4750/5750"
pdf-subtitle: "Homework 1: Introduction to Using Julia"
pdf-header-left: "BEE 4750/5750"
pdf-header-right: "Fall 2026"
pdf-footer-left: "Homework 1: Introduction to Using Julia"
pdf-logo-path: "../../_assets/logos/envsys_logo.png"
date: last-modified
format:
    html:        
        warning: true
        error: true
    ipynb:
        warning: true
        error: true
        code-annotation: below
    typst:
        warning: true
        error: true
        toc: false
        date: "08/24/2026"
execute: 
    echo: true
    eval: true
engine: julia
julia:
  exeflags: ["+1.11.5"]
format-links:
  - format: typst
    text: PDF
    icon: file-earmark-pdf
  - format: ipynb
    text: Notebook
    icon: laptop
---

::: {.content-visible when-format="ipynb"}
**Name**:

**ID**:
:::

::: {.callout-important icon=false}
### Due Date

Thursday, 09/17/26, 9:00pm
:::



## Overview

### Instructions

* Problem 1 asks you to find the equilibria of several 1-D systems models and identify their stability.
* Problem 2 asks you to draw a systems diagram and identify the type of a feedback.
* Problem 3 asks you to find and analyze the equilibria of a modified predatory-prey system.
* Problem 4 asks you to analyze a lake system experiencing phosphorous loading, both feedbacks as well as equilibria and stability.

### Load Environment

The following code loads the environment and makes sure all needed packages are installed. This should be at the start of most Julia scripts.

```{julia}
#| output: false
import Pkg
Pkg.activate(@__DIR__)
Pkg.instantiate()
```

```{julia}
using Plots
using LaTeXStrings
```

## Problems (Total: 50 Points)

::: {.markdown .cell}
### Problem 1 (9)

For each of the following systems models, find (i) any equilibria and (ii) their stabilities.

:::

::: {.markdown .cell}
#### Problem 1.1 (3)

$$\frac{dx}{dt} = 4x^2 - 16$$
:::

::: {.markdown .cell}
#### Problem 1.2 (3)

$$\frac{dx}{dt} = x - x^3$$
:::

::: {.markdown .cell}
#### Problem 1.3 (3)

$$\frac{dx}{dt} = 1 - 2\cos x$$
:::


::: {.markdown .cell}
### Problem 2 (9)

:::
::: {.markdown .cell}
#### Problem 2.1 (5)
Draw a systems diagram for the relationship between global mean temperature, atmospheric CO~2~ concentrations, and ocean CO~2~ concentrations. What are the signs of the interactions between these components and why? What does this suggest about the overall feedback between temperature and the ocean carbon cycle?


::: {.callout-tip}
Think about Henry's law for CO~2~.
:::

:::
::: {.markdown .cell}
#### Problem 2.2 (4)

Of the following quantities related to this system, which are stocks and which are flows?

1. The absorbed mass of CO~2~ in the ocean.
2. The rate at which CO~2~ is absorbed by the ocean from the atmosphere.
3. The yearly increase in global temperature.
4. The heat stored in the ocean.
:::

::: {.markdown .cell}
### Problem 3 (6)

One criticism of the Lotka-Volterra predator-prey equations discussed in class is that the behavior of the system is entirely determined by the initial conditions of the model: a perturbation (like a disease among some of the prey) would permanently change the dynamics of the system and the populations would never recover to their "natural" levels. 

We can "fix" this by adding another term to the model, a population-dependent death rate which causes populations to recover more rapidly at lower populations and die off more rapidly at larger populations. This would take the following form:

$$\begin{aligned}
\frac{dH}{dt} &= b_h H_t - m_h H_t L_t - \gamma_H H_t^2 \\
\frac{dL}{dt} &= b_L L_t H_t - m_L L_t - \gamma_L L_t^2 
\end{aligned}$$


What are the equilibria of the system (bearing in mind that all of the model parameters must be positive; **hint: you should get three**)? What are the stabilities of any non-trivial $(L_t=H_t=0$) equilibria? Comparing this result to the Lotka-Volterra analysis from class, what can you say about the impact of the population-dependent death term on the behavior of the system? 

:::

::: {.cell .markdown}
### Problem 4 (26)

A shallow, temperate, well-mixed lake receiving phosphorus from its catchment. In this lake, phosphorus (P) is the limiting nutrient for algal biomass and whether the lake is oligotrophic or eutrophic. 

The storage level of P in the sediment is primarily determined by the oxygen (O~2~) in the sediment and is thus related to the level of algal biomass (decomposition of dead algae consumes O~2~). P is also lost from the lake system through outflow and permanent deposition in the sediment.

:::

::: {.cell .markdown}
#### Problem 4.1 (4)

Draw a systems diagram for this lake system, capturing the feedback due to the impact of O~2~ on sediment P recycling and its mediation by algal biomass. Is this an amplifying or a dampening feedback loop?

:::

::: {.cell .markdown}
#### Problem 4.2 (3)

Which of the following system quantities are stocks and which are flows?

1. The O~2~ demand induced by decomposing biomass.
2. The sediment P pool.
3. The external P loading in a given year

:::

::: {.markdown .cell}

#### Problem 4.3 (5)


The P concentration of the lake is determined by 
$$\frac{dP}{dt} = L - sP - R(t),$$
where $P$ is the P concentration ($\mu\text{g}/\text{L}$), $L$ is external P loading from runoff ($\mu\text{g}/(\text{L} \cdot \text{yr})$), $s=1\ \text{yr}^{-1}$ is the first-order rate of combined P outflow and permanent deposition, and $R(t)$ ($\mu\text{g}/(\text{L}\cdot\text{yr})$ is the sediment release rate at time $t$.

Since the amount of algal biomass is limited by the P concentration, the sediment release rate $R$ can be written as a function of P instead of time. This can be thought of as consisting of three regimes: (1) when the lake is fully oligotrophic and sediment is fully oxidized, retaining all P; (2) a transitional regime where increasing algae reduces sediment oxygenation, increasing P recycling; (3) when the sediment is releasing at its maximum capacity due to maximum sediment P and/or the ability of bacteria to decompose biomass, and additional biomass will not increase the rate of recycling. We will assume the maximum recycling rate is $20\ \mu\text{g}/\text{L}$, and the transitional regime occurs between $25\ \mu\text{g}/\text{L}$ and $35\ \mu\text{g}/\text{L}$.

Turning this into a piecewise linear model for $R$:
$$
R(P) = \begin{cases}
    0 & \quad \text{if} P \leq 25\ \mu\text{g}/\text{L} \\
    20 \frac{P - 25}{10} & \quad \text{if} 25\ \mu \text{g}/\text{L} < P < 35\ \mu \text{g}/\text{L} \\
    20 & \quad \text{if} P \geq 35\ \mu\text{g}/\text{L}
\end{cases}.
$$
:::

What are the feedback gain(s) for this model in each sediment recycling regime? What does this implify about how a one-off P increase of $1 \mu \text{g}/\text{L}$ would increase the P level of the lake?


::: {.cell .markdown}

#### Problem 4.4 (6)

Find the equilibria of this system assuming external loading of $L=20\ \mu\text{g}/(\text{L} \cdot \text{yr})$. Are they stable or unstable? 

:::

::: {.markdown .cell}
#### Problem 4.5 (8)

What are the impacts to the equilibria of the lake if the external loading decreases to $L=10\ \mu\text{g}/(\text{L} \cdot \text{yr})$ or increases to $L=30\ \mu\text{g}/(\text{L} \cdot \text{yr})$? What does this tell you about how the lake could respond to these different levels of loading?

:::

::: {.markdown .cell}
## References

List any external references consulted, including classmates.
:::
